# Generated by Django 5.0.7 on 2024-09-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
