# Generated by Django 5.0.7 on 2024-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deliveryboy_availability_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
